nextcloud_version: 27.1.4
caddy_version: 2.7.5

nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud

# nextcloud apps
install_talk: true
install_media: true

# php-fpm
php_fpm:
  max_children: 120
  start_servers: 12
  min_spare_servers: 8
  max_spare_servers: 40

# php
opcache:
  interned_strings_buffer: 16

# mariadb
innodb_buffer_pool_size: 1G
remove_unused_authtokens_after_days: 21

# os hardening
os_auditd_max_log_file_action: rotate
