nextcloud_version: 25.0.2
caddy_version: 2.6.2

nextcloud_db_name: nextcloud
nextcloud_db_user: nextcloud

# nextcloud
install_talk: true

# php-fpm
php_fpm:
  max_children: 120
  start_servers: 12
  min_spare_servers: 6
  max_spare_servers: 18

# php
opcache:
  interned_strings_buffer: 16

# mariadb
innodb_buffer_pool_size: 512M

# os hardening
os_auditd_max_log_file_action: rotate