pipeline:
  build:
    image: alpine:3.15
    commands:
      - apk --update add python3
      - python3 -m py_compile plugins/modules/*

  test:
    image: alpine:3.15
    environment:
      NEXTCLOUD_HOST: nextcloud21
      NEXTCLOUD_USER: ansible
      NEXTCLOUD_TOKEN: ansible
    commands:
      - apk --update add ansible py3-requests curl
      - ansible-galaxy collection build
      - ansible-galaxy collection install markuman-nextcloud-*
      - ansible-playbook tests/integration.yml

services:
  - name: nextcloud21
    image: public.ecr.aws/h6n8g0x7/osuv:nc21_it