kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run
    commands:
    - apk --update add curl
    - sleep 2
    - curl http://nextcloud21/

  - name: build
    image: alpine:3.13
    commands:
      - apk --update add python3 py3-pip gcc python3-dev musl-dev libffi libffi-dev openssl-dev openssl
      - pip3 install ansible
      - ansible-galaxy collection build


services:
  - name: nextcloud21
    image: nextcloud:21-apache
    environment:
      NEXTCLOUD_ADMIN_USER: ansible
      NEXTCLOUD_ADMIN_PASSWORD: ansible