namespace: "markuman"
name: "nextcloud"
version: "0.0.1"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GNU GENERAL PUBLIC LICENSE 3 or later"
tags:
    - nextcloud
    - collection
repository: "https://git.osuv.de/m/nextcloud_collection"