namespace: "markuman"
description: bring up your nextcloud usage to the next level 🚀
name: "nextcloud"
version: "9.2.2"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - nextcloud
    - collection
    - devops
    - installation
    - setup
repository: "https://git.osuv.de/m/nextcloud_collection"
issues: https://github.com/markuman/nextcloud_collection/issues
dependencies:
  devsec.hardening: '>=7.14.0'
