namespace: "markuman"
description: bring up your nextcloud usage to the next level 🚀
name: "nextcloud"
version: "8.0.0-dev"
readme: "README.md"
authors:
    - "Markus Bergholz <markuman+spambelongstogoogle@gmail.com>"
license:
    - "GPL-3.0-or-later"
tags:
    - nextcloud
    - collection
repository: "https://git.osuv.de/m/nextcloud_collection"
issues: https://github.com/markuman/nextcloud_collection/issues
