- name: add ubuntu nextcloud system user
  ansible.builtin.user:
    name: "{{ ubuntu_nextcloud_user }}"
    shell: /bin/bash
    comment: Ubuntu Nextcloud System User
    password_expire_max: 99999
    groups:
      - www-data
      - sudo

- name: set authorized_keys file for ubuntu nextcloud user
  ansible.posix.authorized_key:
    user: "{{ ubuntu_nextcloud_user }}"
    state: present
    manage_dir: true
    key: "{{ ubuntu_nextcloud_user_ssh_key_location }}"

- name: Allow ubuntu_nextcloud_user to use sudo without password
  ansible.builtin.copy:
    dest: /etc/sudoers.d/ubuntu_nextcloud_user
    validate: visudo -cf %s
    owner: root
    group: root
    mode: 0644
    content: |
      {{ ubuntu_nextcloud_user }} ALL=(ALL) NOPASSWD:ALL

- name: ssh hardening
  ansible.builtin.include_role:
    name: devsec.hardening.ssh_hardening
