- name: get nextcloud itself
  unarchive:
    src: "https://download.nextcloud.com/server/releases/nextcloud-{{ nextcloud_version }}.zip"
    dest: "/var/www/"
    remote_src: true
    owner: www-data
    group: www-data

- name: install nextcloud
  register: result
  args:
    chdir: /var/www/nextcloud/
  command: >
    sudo -u www-data php occ  maintenance:install --database
    "mysql" --database-name "nextcloud"  --database-user "nextcloud" --database-pass
    "{{ nextcloud_db_password }}" --admin-user "{{ nextcloud_admin_user }}" --admin-pass "{{ nextcloud_admin_password }}"
  failed_when:
    - result.rc == 1
    - '"\"maintenance:install\" is not defined" not in result.stderr'
  changed_when:
    - result.rc == 0

- name: install and enable nextcloud apps
  register: result
  args:
    chdir: /var/www/nextcloud/
  command: "sudo -u www-data php occ app:{{ item }}"
  with_items:
    - enable bruteforcesettings
    - enable twofactor_totp
  failed_when:
    - result.rc == 1
    - '"already installed" not in result.stdout'
  changed_when:
    - result.rc == 0

- name: nextcloud system settings
  args:
    chdir: /var/www/nextcloud/
  command: "sudo -u www-data php occ config:system:set {{ item }}"
  with_items:
    - "trusted_domains 2 --value={{ nextcloud_fqdn }}"
    - memcache.local --value='\OC\Memcache\APCu'
    - overwrite.cli.url --value=https://{{ nextcloud_fqdn }}
    - overwriteprotocol --value="https"
    - htaccess.IgnoreFrontController --value=true

- name: systemd timer service
  ansible.builtin.copy:
    mode: '0755'
    dest: /etc/systemd/system/nextcloudcron.service
    content: |
      [Unit]
      Description=Nextcloud cron.php job

      [Service]
      User=www-data
      ExecStart=/usr/bin/php -f /var/www/nextcloud/cron.php
      KillMode=process

- name: systemd timer
  ansible.builtin.copy:
    mode: '0755'
    dest: /etc/systemd/system/nextcloudcron.timer
    content: |
      [Unit]
      Description=Run Nextcloud cron.php every 5 minutes

      [Timer]
      OnBootSec=5min
      OnUnitActiveSec=5min
      Unit=nextcloudcron.service

      [Install]
      WantedBy=timers.target

- name: start and enable systemd timer
  systemd:
    name: nextcloudcron.timer
    state: started
    enabled: true
