- include_tasks: 01-packages.yml
- include_tasks: 02-user.yml
- include_tasks: 03-mariadb.yml
- include_tasks: 04-php.yml
- include_tasks: 05-caddy.yml
- include_tasks: 06-nextcloud.yml
- include_tasks: 07-coturn.yml
