- name: init root user
  command: >
    sudo mysql -uroot -e "
    UPDATE mysql.user SET plugin='mysql_native_password';  
    SET PASSWORD FOR root@localhost = PASSWORD('{{ mariadb_root_password }}');
    FLUSH PRIVILEGES;"

- include_role:
    name: devsec.hardening.mysql_hardening
  vars:
    mysql_root_password: "{{ mariadb_root_password }}"

- name: root save my.cnf
  ini_file:
    owner: root
    path: "/root/.my.cnf"
    section: client
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0600'
  with_items:
    - option: user
      value: root
    - option: password
      value: "{{ mariadb_root_password }}"

- name: save my.cnf
  ini_file:
    owner: "{{ ubuntu_nextcloud_user }}"
    path: "/home/{{ ubuntu_nextcloud_user }}/.my.cnf"
    section: client
    option: "{{ item.option }}"
    value: "{{ item.value }}"
    mode: '0600'
  with_items:
    - option: user
      value: "{{ nextcloud_db_user }}"
    - option: password
      value: "{{ nextcloud_db_password }}"

- name: init nextcloud user and database
  command: >
    sudo mysql -uroot -e "
    CREATE USER IF NOT EXISTS '{{ nextcloud_db_user }}'@'localhost' IDENTIFIED BY '{{ nextcloud_db_password }}';
    CREATE DATABASE IF NOT EXISTS nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
    GRANT ALL PRIVILEGES ON nextcloud.* TO '{{ nextcloud_db_user }}'@'localhost';
    UPDATE mysql.user SET plugin='mysql_native_password';
    FLUSH PRIVILEGES;"

