- name: determine limit values
  set_fact:
    LIMIT1: "{{ ((ansible_memtotal_mb/1024) | round) * ((ansible_processor_vcpus | pow(ansible_processor_vcpus))+1) }}"
    LIMIT2: "{{ ((ansible_memtotal_mb/1024) | round) * ((ansible_processor_vcpus | pow(ansible_processor_vcpus))+1) * 2 }}"
    LIMIT3: "{{ ((ansible_memtotal_mb/1024) | round) * ((ansible_processor_vcpus | pow(ansible_processor_vcpus))+1) * 3 }}"

- name: nginx hardening
  include_role:
    name: devsec.hardening.nginx_hardening
  vars:
    nginx_limit_conn: "default {{ LIMIT2 | int }}"
    nginx_client_max_body_size: 512M
    nginx_client_body_buffer_size: 512M
    nginx_client_body_timeout: 300s
    nginx_client_header_timeout: 300s
    nginx_ssl_protocols: TLSv1.3

- name: nextcloud nginx config
  template:
    dest: "/etc/nginx/sites-available/{{ nextcloud_fqdn }}"
    src: nginx_80.j2
    owner: root
    group: root

- name: Create a symbolic link
  ansible.builtin.file:
    src: "/etc/nginx/sites-available/{{ nextcloud_fqdn }}"
    dest: "/etc/nginx/sites-enabled/{{ nextcloud_fqdn }}"
    owner: root
    group: root
    state: link

- name: Create and Install Cert Using {{ certbot_plugin }} Plugin
  command: "certbot --nginx -d  {{ nextcloud_fqdn }} -m {{ lets_encrypt_mail }} --agree-tos --noninteractive --redirect"

- name: Set Letsencrypt Cronjob for Certificate Auto Renewal
  cron:
    name: letsencrypt_renewal
    special_time: monthly
    job: "/usr/bin/certbot renew"

- name: nextcloud nginx config
  template:
    dest: "/etc/nginx/sites-available/{{ nextcloud_fqdn }}"
    src: nginx.j2
    owner: root
    group: root

- name: setup php-fpm
  lineinfile:
    dest: /etc/php/7.4/fpm/pool.d/www.conf
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ;env[HOSTNAME] = $HOSTNAME
      line: env[HOSTNAME] = $HOSTNAME
    - regexp: ;env[PATH] = /usr/local/bin:/usr/bin:/bin
      line: env[PATH] = /usr/local/bin:/usr/bin:/bin
    - regexp: ;env[TMP] = /tmp
      line: env[TMP] = /tmp
    - regexp: ;env[TMPDIR] = /tmp
      line: env[TMPDIR] = /tmp
    - regexp: ;env[TEMP] = /tmp
      line: env[TEMP] = /tmp
    - regexp: pm.max_children.*
      line: pm.max_children = {{ LIMIT3 | int }}

- name: setup php
  lineinfile:
    dest: /etc/php/7.4/fpm/php.ini
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ;cgi.fix_pathinfo=1
      line: cgi.fix_pathinfo=0
    - regexp: memory_limit = 128M
      line: memory_limit = 1G
    - regexp: ;opcache.enable=1
      line: opcache.enable=1
    - regexp: ;opcache.enable_cli=0
      line: opcache.enable_cli=1
    - regexp: ;opcache.memory_consumption=128
      line: opcache.memory_consumption=128
    - regexp: ;opcache.interned_strings_buffer=8
      line: opcache.interned_strings_buffer=8
    - regexp: ;opcache.max_accelerated_files=10000
      line: opcache.max_accelerated_files=10000
    - regexp: ;opcache.revalidate_freq=2
      line: opcache.revalidate_freq=1
    - regexp: ;opcache.save_comments=1
      line: opcache.save_comments=1

- name: setup php cli
  lineinfile:
    dest: /etc/php/7.4/cli/php.ini
    state: present
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - regexp: ;cgi.fix_pathinfo=1
      line: cgi.fix_pathinfo=0

- name: setup php cli apc
  lineinfile:
    dest: /etc/php/7.4/cli/php.ini
    state: present
    line: apc.enable_cli=1

- name: restart services
  systemd:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
    - php7.4-fpm