- name: uprade all packages first
  apt:
    update_cache: yes
    state: latest
    upgrade: yes

- name: install apache, php and mariadb
  apt:
    update_cache: yes
    state: latest
    name:
      - nginx
      - mariadb-server
      - mariadb-client
      - ufw
      - vnstat
      - python3-pymysql
      - php-fpm
      - php-gd
      - php-mysql
      - php-curl
      - php-xml
      - php-zip
      - php-intl
      - php-mbstring
      - php-bz2
      - php-json
      - php-apcu
      - php-imagick
      - php-gmp
      - php-bcmath
      - imagemagick
      - libmagickcore-6.q16-6-extra

- name: ufw - limit ssh port 
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: ufw - allow http & https ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443

- name: ufw - enable
  community.general.ufw:
    state: enabled

- name: os hardening
  include_role:
    name: devsec.hardening.os_hardening
