- name: set hostname
  hostname:
    name: "{{ nextcloud_fqdn.split('.')[0] }}"

- name: resolv myself
  command: host "{{ nextcloud_fqdn }}"
  register: myself

- name: complete /etc/hosts
  lineinfile:
    name: /etc/hosts
    line: "{{ myself.stdout_lines[0].split(' ')[-1] }} {{ nextcloud_fqdn }} {{ nextcloud_fqdn.split('.')[0] }}"

- name: uprade all packages first
  apt:
    update_cache: yes
    state: latest
    upgrade: yes

- name: install apache, php and mariadb
  apt:
    update_cache: yes
    state: latest
    name:
      - nginx
      - mariadb-server
      - mariadb-client
      - ufw
      - vnstat
      - python3-pymysql
      - python3-certbot-nginx
      - php-fpm
      - php-gd
      - php-mysql
      - php-curl
      - php-xml
      - php-zip
      - php-intl
      - php-mbstring
      - php-bz2
      - php-json
      - php-apcu
      - php-imagick
      - php-gmp
      - php-bcmath
      - imagemagick
      - libmagickcore-6.q16-6-extra

- name: ufw - limit ssh port 
  community.general.ufw:
    rule: limit
    port: ssh
    proto: tcp

- name: ufw - allow http & https ports
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  with_items:
    - 80
    - 443
  

- name: ufw - http & https egress
  community.general.ufw:
    direction: out
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
  with_items:
    - port: 80
      proto: tcp
      desc: http
    - port: 443
      proto: tcp
      desc: https
    - port: 53
      proto: udp
      desc: dns
    - port: 123
      proto: udp
      desc: ntp

- name: ufw - enable
  community.general.ufw:
    state: enabled

- name: os hardening
  include_role:
    name: devsec.hardening.os_hardening
