- name: reload ufw
  community.general.ufw:
    state: reloaded

- name: restart caddy
  systemd:
    name: caddy
    state: restarted

- name: restart php-fpm
  systemd:
    name: php8.1-fpm
    state: restarted

- name: restart coturn
  systemd:
    name: coturn
    state: restarted
